//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gitarist.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chord
    {
        public int id { get; set; }
        public string name { get; set; }
        public byte[] description { get; set; }
        public string imageUrl { get; set; }
    }
}
