//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gitarist.Models.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gitaristEntities : DbContext
    {
        public gitaristEntities()
            : base("name=gitaristEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArtistForeign> ArtistForeigns { get; set; }
        public virtual DbSet<ArtistRusian> ArtistRusians { get; set; }
        public virtual DbSet<Chord> Chords { get; set; }
        public virtual DbSet<SongForeign> SongForeigns { get; set; }
        public virtual DbSet<SongRusian> SongRusians { get; set; }
        public virtual DbSet<Theme> Themes { get; set; }
    }
}
