//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gitarist.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SongForeign
    {
        public long id { get; set; }
        public Nullable<int> artistId { get; set; }
        public Nullable<int> themeId { get; set; }
        public bool isNew { get; set; }
        public string name { get; set; }
        public string chords { get; set; }
        public bool deleted { get; set; }
        public bool isPopular { get; set; }
        public System.DateTime datecreate { get; set; }
        public string clearUrlName { get; set; }
    
        public virtual ArtistForeign ArtistForeign { get; set; }
        public virtual Theme Theme { get; set; }
    }
}
